=== davidhay/spring-rabbit/src/main/resources/schema/Position-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"minProperties": 1,
	"properties": {
		"positionID": {
			"type": "integer",
			"minLength": 1,
			"maxLength": 15
		},
		"changeDeleteIndicator": {
			"type": "string",
			"enum": [
				"C",
				"D"
			]
		},
		"positionNumber": {
			"type": "integer",
			"maxLength": 10
		},
		"positionTitle": {
			"type": "string",
			"maxLength": 60
		},
		"occupationCode": {
			"type": "string",
			"maxLength": 5
		},
		"areaOfWork": {
			"type": "string",
			"maxLength": 50
		},
		"secondSpeciality": {
			"type": "string",
			"maxLength": 5
		},
		"deaneryNumber": {
			"type": "string",
			"minLength": 1,
			"maxLength": 30
		},
		"managingOffice": {
			"type": "string",
			"maxLength": 10
		},
		"odsCode": {
			"type": "string",
			"maxLength": 30
		},
		"gradeTrust": {
			"type": "string",
			"maxLength": 3
		},
		"gradePayscale": {
			"type": "string",
			"maxLength": 10
		},
		"gradeDesc": {
			"type": "string",
			"maxLength": 60
		},
		"workplaceOrg": {
			"type": "string",
			"maxLength": 30
		}
	},
	"required": [
		"positionID",
		"deaneryNumber"
	]
}

=== davidhay/spring-rabbit/src/test/resources/json/valid/position-example-1.json
{
	"positionID": 123456789123456,
	"changeDeleteIndicator": "D",
	"positionNumber": 1234567890,
	"positionTitle": "test",
	"occupationCode": "ACODE",
	"areaOfWork": "Around",
	"secondSpeciality": "Spec",
	"deaneryNumber": "NTH/RTFED/040/STR/210",
	"managingOffice": "Northern",
	"odsCode": "CodingCode",
	"gradeTrust": "NTH",
	"gradePayscale": "High",
	"gradeDesc": "Senior",
	"workplaceOrg": "WTO"
}
